-- 조건1. 총주문량 3000 초과
-- 조건2. 주성분: 과일
-- 조건3. 총주문량 큰 순서

SELECT f.FLAVOR
FROM FIRST_HALF as f
JOIN ICECREAM_INFO as i
    ON f.FLAVOR = i.FLAVOR
WHERE TOTAL_ORDER > 3000
    AND INGREDIENT_TYPE LIKE "fruit%"
ORDER BY f.TOTAL_ORDER DESC;

# SELECT *
# FROM FIRST_HALF
# ORDER BY TOTAL_ORDER;