# 1. 대여시작일 2022년 9월
# 2. 대여기간 30일이상 '장기 대여', 아니면 '단기 대여' (컬럼명 : RENT_TYPE)
# 3. 대여기록 ID 내림차순

SELECT HISTORY_ID, CAR_ID, 
    DATE_FORMAT(START_DATE, "%Y-%m-%d") AS START_DATE, 
    DATE_FORMAT(END_DATE, "%Y-%m-%d") AS END_DATE, 
    CASE
        WHEN TIMESTAMPDIFF(DAY,START_DATE,END_DATE)>=29
        THEN '장기 대여'
        ELSE '단기 대여'
    END AS RENT_TYPE
    # TIMESTAMPDIFF(DAY,START_DATE,END_DATE) AS HELLO
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, "%Y-%m") = "2022-09"
ORDER BY HISTORY_ID DESC;
# ORDER BY HELLO DESC;